version: '3.8'

services:
  consultacnpj:
    image: openjdk:17-jdk-alpine
    container_name: consultacnpj
    volumes:
      - ./target/consultacnpj-0.0.1-SNAPSHOT.jar:/app/consultacnpj.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app/consultacnpj.jar"]
